config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/content")

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response

  get "/metrics/(*base_path)", to: "metrics#show", as: :metrics, format: false

  get "/site-improve-redirect/quality-assurance/(*base_path)", to: "siteimprove_redirect#quality_assurance"
  get "/site-improve-redirect/accessibility/(*base_path)", to: "siteimprove_redirect#accessibility"
  get "/site-improve-redirect/seo/(*base_path)", to: "siteimprove_redirect#seo"
  get "/site-improve-redirect/policy/(*base_path)", to: "siteimprove_redirect#policy"

  get "/content", to: "content#index"
  get "/content/export_csv", to: "content#export_csv"
  get "/documents/:document_id/children", to: "documents#children", format: false
  mount GovukPublishingComponents::Engine, at: "/component-guide" unless Rails.env.production?
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  include PaginationHelper

  DEFAULT_ORGANISATION_ID = "all".freeze

  layout "application"
  before_action :set_constants, only: [:index]

  def set_constants
    @fullwidth = true
  end

  def index
    search_results = FindContent.call(search_params)

    @filter = FilterPresenter.new(search_params)
    @presenter = ContentItemsPresenter.new(search_results, search_params)
  end

  def export_csv
    @recipient = current_user.email

    start_time_string = Time.zone.now.to_s
    CsvExportJob.perform_async(search_params.stringify_keys, @recipient, start_time_string)
  end

private

  def search_params
    @search_params ||= begin
      defaults = {
        date_range: "past-30-days",
        organisation_id: DEFAULT_ORGANISATION_ID,
        document_type: "",
        sort: "upviews:desc",
      }

      defaults.merge(
        params.permit(
          :date_range,
          :organisation_id,
          :document_type,
          :page,
          :search_term,
          :sort,
        ).to_h.symbolize_keys,
      )
    end
  end
end

app/views/content/_page_title.html.erb
<%= link_to item.title,
  metrics_path(item.base_path, date_range: date_range),
  class: 'content-item__link',
  data: {
    'gtm-id': 'content-item-link',
    'gtm-item-document-type': item.raw_document_type,
  } %>
<br>
<span class="base-path">/<%= CGI::unescape(item.base_path) %></span>

app/views/content/_table_data_description.html.erb
<h1 class="table-caption">
    <% if pagination.total_results > 0 %>
        Showing
        <span class="table-caption__param"><%= pagination.formatted_total_results %></span> <%= 'result'.pluralize(pagination.total_results) %>
    <% else %>
        <span class="table-caption__param"><%= I18n.t('no_matching_results') %></span>
    <% end %>
    <% if filter.search_terms? %>
        for '<span class="table-caption__param"><%= filter.search_terms %></span>'
    <% end %>
    <% if filter.document_type? && filter.document_type_id != "all" %>
        for <span class="table-caption__param"><%= filter.document_type_name.humanize(capitalize: false) %></span>
    <% else %>
        for <span class="table-caption__param">all document types</span>
    <% end %>
    from <span class="table-caption__param">
    <% if filter.organisation_name == "All organisations" %>
        all organisations
    <% else %>
        <%= filter.organisation_name %>
    <% end %>
    </span>
</h1>

app/views/content/export_csv.html.erb
<% content_for :title, "Sending CSV export" %>
<% content_for :page_class, "content-data__metrics" %>
<% content_for :local_nav do %>
  <div class="local-nav govuk-grid-column-one-quarter">
    <a href="/content" class="local-nav__search-link govuk-link govuk-link--no-visited-state" data-gtm-id="back-link">Search</a>
  </div>
<% end %>
<%= render(partial: 'components/ga4_notice') %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l">Sending the CSV export</h1>
    <p>The data you exported is on its way. We'll send an email to <%= @recipient %> with a link to download the CSV.</p>
    <p>Most emails arrive within 15 minutes. If you do not receive an email within 30 minutes, raise a <a href="https://support.publishing.service.gov.uk/">support request</a>.</p>
  </div>
</div>

app/views/content/index.html.erb
<% content_for :title, @presenter.title %>
<% content_for :page_class, "content-data__index" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-full ga-data-notice-column">
    <%= render(partial: 'components/ga4_notice') %>
  </div>
</div>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-one-quarter">
      <div class="filters-control__wrapper filter--hidden" data-module="filter-toggle">
        <span class="filters-control filters-control--hide filter--hidden">
          <a href="" class="govuk-link filters-control__link filters-control__link--hide">Hide filters</a>&nbsp;&#x25B2;
        </span>
        <span class="filters-control filters-control--show filter--hidden">
          <a href="" class="govuk-link filters-control__link filters-control__link--show">Show filters</a>&nbsp;&#x25BC;</span>
      </div>
      <div class="filter-form">
        <%= form_tag content_path,
          method: 'get',
          name: 'organisation-picker',
          id: 'filter-form',
          data: { 'gtm-id': 'filters-form' } do %>
          <input type="hidden" name="submitted" value="true" >
          <%= render "components/time_select", {
            current_selection: @presenter.time_period,
            compact: true,
            base_path: "/",
            custom_month_selected: custom_month_selected(@presenter.time_period),
            dates: time_select_options(TimeSelectHelper::CONTENT_PAGE_TIME_PERIODS)
          } %>

          <div class="filter-form__filters">
            <%= render "govuk_publishing_components/components/input", {
                label: {
                  text: "Search for a title or URL"
                },
                name: "search_term",
                tabindex: 0,
                value: params[:search_term],
              } %>

          <%= render "components/accessible_autocomplete",
              {
                id: 'document_type',
                label: {
                  text: "Document type"
                },
                options: @filter.document_type_options,
                selected_option: @filter.selected_document_type(params)
              }
          %>
          <%= render "components/accessible_autocomplete",
              {
                id: 'organisation_id',
                label: {
                  text: "Organisation"
                },
                options: @filter.organisation_options,
                selected_option: @filter.selected_organisation(params)
              }
          %>

            <%= render "govuk_publishing_components/components/button", {text: "Filter"} %>

            <a href="/content" class="govuk-link govuk-body-s filter-form__clear-link" data-gtm-id="clear-filters">Clear all filters</a>
          <% end %>
        </div>

            <hr class="govuk-section-break govuk-section-break--s govuk-section-break--visible">
            <p>
              <a href="<%= content_export_csv_path(@presenter.search_parameters) %>"
                 class="govuk-link govuk-body-s download-link" data-gtm-id="csv-download-link">
                Download all data in CSV format
              </a>
            </p>
        </div>
    </div>
    <div class="govuk-grid-column-three-quarters">
      <div class="table-wrapper sortable-table">
        <table class="table govuk-table"
          data-gtm-total-results="<%= @presenter.pagination.total_results %>"
          data-gtm-page="<%= @presenter.pagination.page %>">
          <caption class="govuk-table__caption">
            <%= render('table_data_description', pagination: @presenter.pagination, filter: @filter) %>
          </caption>
          <thead class="govuk-table__head" data-gtm-id="table-header">
            <tr class="govuk-table__row">
            <% TableHeaderHelper::HEADER_NAMES.each do |header| %>
              <% sort_direction = @presenter.sort.direction if (header == @presenter.sort.key) %>
              <th class="govuk-table__header <% if sort_direction.present? %>govuk-table__header--sorted<% end %>"
                scope="col"
                role="columnheader"
                aria-sort="<%= aria_sort(sort_direction) %>"
                data-gtm-id="<%= header %>-column">
                <% if header.in? TableHeaderHelper::HEADERS_WITH_SORT_ENABLED %>
                  <a href="<%= url_for(request.params.merge(sort: sort_param(header, sort_direction))) %>"
                    data-gtm-id="sort-link"
                    class="table__sort-link <% if sort_direction.present? %> table__sort-link--<%= sort_direction %> <% end %>">
                    <%= t(".table.headers.#{header}", default: :"metrics.#{header}.title") %>
                  </a>
                <% else %>
                  <%= t(".table.headers.#{header}", default: :"metrics.#{header}.title") %>
                <% end %>
                <br>
                <% if include_help_icon?(header) %>
                  <a href="/help/?hkey=<%= header %>" data-toggle="modal" data-target="modal-<%= header %>" data-gtm-id="help-icon" class="table__header-help">
                      <%= image_tag(
                        (sort_direction.present? ? 'question_mark_inverse.svg' : 'question_mark_default.svg'),
                        alt: 'Help')
                      %>
                  </a>
                <% end %>
              </th>
            <% end %>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
          <% @presenter.content_items.each do |item| %>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell" data-gtm-id="title-column">
                <%=
                  render(
                    partial: 'components/table_column_page_title',
                    locals: {
                      item: item,
                      date_range: @presenter.time_period
                    }
                ) %>
              </td>
              <td class="govuk-table__cell govuk-table__cell--shaded" data-gtm-id="document_type-column"><%= item.document_type %></td>
              <td class="govuk-table__cell govuk-table__cell--numeric" data-gtm-id="upviews-column"><%= item.upviews %></td>
              <td class="govuk-table__cell govuk-table__cell--shaded" data-gtm-id="satisfaction-column">
                <% if item.satisfaction_percentage %>
                    <%= item.satisfaction_percentage %>
                    <span class="satisfaction-column__responses"> (<%= item.satisfaction_responses %>) </span>
                <% else %>
                   <%= item.satisfaction_responses %>
                <% end %>
              </td>
              <td class="govuk-table__cell govuk-table__cell--numeric" data-gtm-id="searches-column"><%= item.searches %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
        </div>
        <%if @presenter.pagination.total_results == 0 %>
          <div class="no-results govuk-body ">
            <h2 class="no-results__header">Sorry, we couldn’t find any results matching your selection</h2>

              <p class="govuk-!-font-size-16">To improve your search results:</p>
              <ul class="govuk-list govuk-list--bullet govuk-!-font-size-16">
              <li>check your spelling</li>
              <li>try the full URL or keywords instead of part of a URL</li>
              <li>remove filters</li>
              <li>come back tomorrow if the content was first published today</li>
              </ul>
              <p class="govuk-!-font-size-16">Content Data does not include services, campaigns, PDFs or blogs.</p>
          </div>
        <% end %>

        <div data-gtm-id="pagination-links">
          <%= render "govuk_publishing_components/components/pagination", navigation_links(@presenter) %>
        </div>
    </div>
</div>

<% content_for :modals do %>
  <% TableHeaderHelper::HEADER_NAMES.each do |header| %>
    <% if include_help_icon?(header) %>
      <%= render "govuk_publishing_components/components/modal_dialogue", {
        id: "modal-#{header}",
        wide: false
      } do %>
        <h1 class="govuk-heading-l"><%= t(".table.headers.#{header}", default: :"metrics.#{header}.title") %></h1>
        <p class="govuk-body"><%= t(".table.headers.#{header}", default: :"metrics.#{header}.about") %></p>
      <% end %>
    <% end %>
  <% end %>
<% end %>